madepu81-invineca

Create help page for IrvineCA

---

lorih95-chicago.md

Lorih95 chicago

---

robertpragai-montreal.md

What type of feedback you want is great to put in this box.

Add some headers to fill in later

---

kavehkh-prague-cz.md

are answers enough to merge to Master or I should add more concrete info here?
@githubteacher FYI ;)

Kavehkh prague cz

---

sorinr-bucharest.md

Anyone that's been to Bucharest - have you spotted some secret places?

sorinr add hometown

---

dmaltsman-northbrook.md

Add cool places to shop, eat and exercise in Northbrook, IL

Dmaltsman add hometown

---

githubteacher-orlando.md

@crichID what would you like to do in Orlando?
Has anyone done things they liked in Central Florida? Non-touristy things in particular 😄

Githubteacher add hometown

---

githubbwlaker.md

Anyone that's been to Chicago - have you done any local stuff you enjoy? 
@krgroseclose you keeping up?

Githubbwlaker chicago

---

tonomoshia-ftlauderdale.md

Does anyone know good local stuff to do in Fort Lauderdale? :100:  :tropical_drink: :bike: :palm_tree: :night_with_stars:

Tonomoshia add hometown

---

smc29-kildeer.md

- Has anyone been to the small NW Chicago suburb of Kildeer?
- If you live nearby (Lake Zurich, Barrington, Long Grove), can you think of anything else to do?

Smc29 kildeer

---

nishchit14-surat
nishchit14-surat.md

Creating pull request
Anybody from india, gujarat, surat ?

Nishchit14 add hometown

---

irini-sanfrancisco.md

Any good questions you might want to get some info?
:+1: :tractor: :last_quarter_moon: :cactus: :camel:

dija-SanFrancisco-CA

---

lisacasq-belfast.md

Anyone that's been to Belfast - have you done any local stuff you enjoy?
:smile:

Lisacasq add hometown

---

wrays-austin.md

Wrays add austin

---

mcgonagall-SanFrancisco.md

Created a SF list including some details on great restaurants!

Mcgonagall   san francisco

---

freebong3-seoul.md

Anyone that's been to Seoul -- have you done any local stuff you enjoy? :roller_coaster: :japanese_castle: 
@tester what kinds of thing would you like to do if you ever visit Seoul?

Freebong3 add hometown

---

Charlotte

Anyone that's been to Charlotte - have you done any local stuff that you've enjoyed.  
:football: 
:grinning:

Ultramag add Charlotte

---

seannittner-mendocino.md

Any one that has traveled to Mendocino - did you get a chance to see ten mile beach? 
@githubteacher ever do any training up in Mendo?

Seannittner add hometown

---

allysonc-atlanta.md

add items under headers
@stevencericson what would you like to do if you ever visit Atlanta?
:bear:

Allysonc add atlanta

---

grecojava-rohnert-park-ca.md

here's some info about Rohnert Park :hamburger:

Grecojava add hometown

---

fomdeveloper-spain.md

Anyone thats been to Granada-Spain, have you done any local stuff you enjoy? ☀️ 
@githubteacher what kind of things would you like to do if you ever visit Granada-Spain?

Fomdeveloper add hometown

---

mnicoli1-kent.md

Has anyone actually even been to kent to give me any ideas :-1:

Mnicoli1 1

---

katieevans8-rancho-cucamonga.md

**First pull request**
Any suggestions for Places to Eat?  :hamburger: :beer: :sushi:

Katieevans8 add hometown

---

krgroseclose-Hudson, OH

Anyone that;s been to Orlando - Why are we talking about vacation instead of tech? :D
@jcon5

Krgroseclose hudson,oh

---

stevencericson-palatine.md

If you have been to Palatine, what did you like there?
:+1:

Stevencericson add hometown

---

onurbabat-bethlehem.md

Anyone thats been to Bethlehem- have you done any local stuff you enjoy? :factory:  :christmas_tree:

Onurbabat add bethlehem

---

jchue-losangeles.md

Anyone know any additional local spots in LA? 😎

Jchue add hometown

---

dhanwade12-bristol.md

For you to review my work
@thube12 please review

Dhanwade12 myhome town

---

lgrundel--Philly.md

stuff to do in Philly anyone?
@someone please comment

added some headers

---

ubuntux-angeles-city.md

Anyone that's been to Angeles City -- have you done any local stuff you enjoy? 🎉 
@githubteacher what kinds of things would you like to do if you ever visit the Philippines? 👪

Ubuntux add hometown

---

ismaelcrespo-madrid.md

This is a pull request :palm_tree:  :mouse:

Ismaelcrespo add hometown

---

sbohms-SiouxFalls.md

Anyone that's been to Sioux Falls?

Sbohms sioux falls

---

lisacasq-belfast.md

added Places to shop

---

pune.md
ryanmorillo-detroit.md

Not really in detroit, but everything is in the 'burbs.

added the crapple

---

yoanarios-montreal.md

I would like to know if someone has somme suggestion about good places to eat.:snowman:

Yoanarios add hometown

---

bondanc-bloomington.md

Bondanc   add hometown

---

RMChapple-Belfast-UK.md

RMChapple add hometown

---

licjapodaca-mexicali-mexico.md

Anyone that's been to Mexicali, Mexico - have you done any local stuff you enjoy? :mouse: 
@crichid Whats kinds of things would you like to do if you ever visit Mexicali?

Licjapodaca add hometown

---

Farfi-barcelona.md

Does anyone know what to do in Barcelona? :see_no_evil:

Farfi add hometown

---

jsebastiantello-StLouis.md

What are your favorite places in St. Louis?

Jsebastiantello add st louis

---

jcon5-Cleveland.md

Does anyone know any good places to eat in Cleveland? :chocolate_bar: :beers: 
@krgroseclose Hi!

Jcon5 add hometown

---

frankhzm-chicago.md

Anyone going to Chicago -- Are there any things in particular that you're interested in exploring?
:+1:

Frankhzm add hometown

---

jpalmer42-stratford.md

@githubteacher do you often work outside in the beautiful weather you have? :palm_tree:

Jpalmer42 add hometown

---

pdevans50-atlanta.md

Pdevans50 add atlanta

---

ascii79-sat.md

Anyone that's been to San Antonio -- have you done any local stuff you enjoy ?
:whale:

Ascii79 add hometown

---

digitalemcee-losangeles.md

Any other things you like to do in Los Angeles, @mendyslaton?
Outside of places and eats? 🍴 🚲 ☀️

Digitalemcee add hometown

---

kengodoy-losangeles.md

Just adding more info regarding this.

Adding my hometown

---

jschunk58-AmericanCanyon.md

Comments on hometown
@GrecoJava any ideas new ideas on things to do in Napa?

Jschunk58 add hometown file

---

billbingham-northbrook-nd

@sharonmungai will this get to you - probably not because not collaborator

Billbingham northbrook branch

---

IonaWillett-Belfast.md

Anyone that's been to Belfast - have you done any local stuff you enjoy?
@RMChapple what kinds of things would you like to do if you ever visit Belfast

Iona willett add hometown

---

noelnoone-donegal.md

Anyone been to Donegal?
If so where, when and with whom.
:golf: :fish: :bikini:

noelnoone-donegal

---

fabgonzalez-mt-vernon.md

I still pretty new in this town -- have you done any local stuff you enjoy?
:bear: free camping zones

Fabgonzalez add hometown

---

mixolidia-miami.md

Does anyone that's been to Miami done any local stuff you enjoy? 🐚 🌴 
@brianamarie what kinds of things would you like to do if you ever visit Miami, FL?

Mixolidia add hometown

---

ccnas273-bowie-md.md

Need to fill in more info...anyone with good ideas?

added some headers to fill in later about Maryland

---

tamistcRackspace-austin.md

Anyone that's been to Austin have you done any local stuff you enjoy?
:ocean: :palm_tree: 
@allysonc what kinds of things would you like to do when you visit Austin?

Tamistc rackspace add hometown

---

digitalemcee-losangeles.md

First Desktop Branch

---

hfish13-Cluj.md

Added lines
and stiff 
any ideeas?
:+1: :+1:

Hfish13 local

---

hfish13-Cluj.md

Reverts githubteacher/everyone-may-2016#310

Revert "Hfish13 local"

---

hamid914-shahrekord.md

Hamid914 local

---

sktay-sanjose.md

What secret places do you suggest for San Jose?

Sktay local

---

krgroseclose-Hudson, OH

Krgroseclose local

---

grecojava-rohnert-park-ca.md

added North Bay App Developers

updated with more stuff to do

---

freebong3-seoul.md

What kind of food do ppl expect when they visit Seoul?

Freebong3 local

---

dhanwade12-bristol.md

Added more things to do and places to eat and shop

Dhanwade12 local

---

ycpatel813-Surat-India.md

Surat detail
@Nishchit14  wel done :+1:

add some detail about surat

---

anniegiturgun-annapolis.md

What kind of food do people expect when visiting Annapolis?

Anniegiturgun local

---

jchue-losangeles.md

What kind of food do people expect when they visit Orlando?

jchue local

---

katieevans8-rancho-cucamonga.md

Please review.
What kind of food do people want to eat?

Katieevans8 local

---

wrays-austin.md

See the additions i made
Does it seem right?

Wrays local

---

mixolidia-miami.md

Please review description of places. Do you need anymore information?
Also, what kind of food do people expect when they visit Miami, FL?

Mixolidia local

---

githubteacher-johnatcl.md
githubteacher-orlando.md

What kind of food do people expect when they visit Orlando?

Githubteacher local

---

sbohms-SiouxFalls.md

What kind of food do people expect in Sioux Falls?

Sbohms local

---

onurbabat-bethlehem.md

What kind of food people expect when they visit Bethlehem?

Onurbabat local

---

fabgonzalez-mt-vernon.md

What kind of food do people expect when they visit Ohio

Fabgonzalez local

---

irini-sanfrancisco.md

Dijazz localbranch

---

ubuntux-angeles-city.md

What kind of food do people expect when they visit Angeles City, Philippines?

Ubuntux local

---

kodali9-washington.md

what kind of food do people expect

Kodali9 local

---

Farfi-barcelona.md

How many languages people speak in Barcelona?

Farfi local

---

ascii79-sat.md
tonyjobson-london.md

playing with updates from a local gitgub

Tonyjobson local

---

ismaelcrespo-madrid.md

Modified my file to add some new spots.

Ismael local

---

jcon5-Cleveland.md

Jcon5 Local

---

githubteacher-orlando.md

Opening PR to demonstrate merge conflict

add gatorland for merge conflict

---

8amlaser-sanfrancisco.md

What do ppl expect to do in SF?

Need to add some items

---

ryanmorillo-detroit.md
thube12-Pune.md
trees

Newcastle uk

---

githubteacher-orlando.md
lisacasq-belfast.md
ls-xxx.md
tonyjobson-london.md

my locally added file

---

githubteacher-orlando.md
lisacasq-belfast.md
ls-xxx
tonyjobson-london.md

Reverts githubteacher/everyone-may-2016#296

Revert "my locally added file"
